name: Deploy to Preview Channel

on:
  push:
    branches:
      - main

env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  PROJECT_ID: gaia-capstone04-prd
  GAR_LOCATION: asia-southeast1
  REPOSITORY: cloud-run-source-deploy
  SERVICE: kopipes-backend
  REGION: asia-southeast1

jobs:
  build_and_preview:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: ./
        run: npm install
      - name: Building the project
        working-directory: ./
        run: npm run build

      - run: npm install -g firebase-tools

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - run: firebase use gaia-capstone06-prd
      - run: firebase deploy --only hosting
